

main: beth_client.c client.c packet_handler.c print_packets.c serial.c buffer.c
	gcc -Wall -O3 -o client beth_client.c client.c packet_handler.c print_packets.c serial.c buffer.c
clean:	
	rm -rf *.o 